### ISSUE TITLE
TypeError: Linear.forward() got an unexpected keyword argument 'scale'

### ISSUE THREAD

**Issue by YuyangXueEd** [Shilin-LU/MACE#19]
Hi Lu,

I ran into some mistake as I did not change the training code as it is. 

The code I was running is:

`CUDA_VISIBLE_DEVICES=0 python training.py configs/object/erase_mickymouse.yaml`

where `erase_mickymouse.yaml` is a copy of `erase_shape` but I changed to the object to `micky-mouse`. However, it gets the error:

```
11/11/2024 12:04:30 - INFO - src.cfr_lora_training - ***** Running training *****
11/11/2024 12:04:30 - INFO - src.cfr_lora_training -   Num examples = 8
11/11/2024 12:04:30 - INFO - src.cfr_lora_training -   Num batches each epoch = 8
11/11/2024 12:04:30 - INFO - src.cfr_lora_training -   Num Epochs = 7
11/11/2024 12:04:30 - INFO - src.cfr_lora_training -   Instantaneous batch size per device = 1
11/11/2024 12:04:30 - INFO - src.cfr_lora_training -   Total train batch size (w. parallel, distributed & accumulation) = 1
11/11/2024 12:04:30 - INFO - src.cfr_lora_training -   Gradient Accumulation steps = 1
11/11/2024 12:04:30 - INFO - src.cfr_lora_training -   Total optimization steps = 50
Using relation-focal importance sampling, which can make training more efficient
                  and is particularly beneficial in erasing mass concepts with overlapping terms.
Steps:   0%|                                                                                                                                                      | 0/50 [00:00<?, ?it/s]==================================================================
Concept 0: micky mouse in a snapshot
==================================================================
Traceback (most recent call last):
  File "/netdisk/users/Yuyang/Reimplementation/test/MACE/training.py", line 37, in <module>
    main(conf)
  File "/netdisk/users/Yuyang/Reimplementation/test/MACE/training.py", line 16, in main
    cfr_lora_training(conf.MACE)
  File "/netdisk/users/Yuyang/Reimplementation/test/MACE/src/cfr_lora_training.py", line 522, in main
    model_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/diffusers/models/unets/unet_2d_condition.py", line 1216, in forward
    sample, res_samples = downsample_block(
                          ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/diffusers/models/unets/unet_2d_blocks.py", line 1288, in forward
    hidden_states = attn(
                    ^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/diffusers/models/transformers/transformer_2d.py", line 442, in forward
    hidden_states = block(
                    ^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/diffusers/models/attention.py", line 507, in forward
    attn_output = self.attn1(
                  ^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/diffusers/models/attention_processor.py", line 495, in forward
    return self.processor(
           ^^^^^^^^^^^^^^^
  File "/netdisk/users/Yuyang/Reimplementation/test/MACE/src/mace_lora_atten_processor.py", line 138, in __call__
    return attn.processor(attn, hidden_states, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/netdisk/users/Yuyang/Reimplementation/test/MACE/src/mace_lora_atten_processor.py", line 43, in __call__
    query = attn.to_q(hidden_states, scale=scale)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Linear.forward() got an unexpected keyword argument 'scale'
Steps:   0%|  
```

It seems like a attention processor issue. Any idea how to solve it?

Looking forward to your reply. Thank you very much!

**Comment by Shilin-LU** [comment]
I haven't encountered this error before. Does this error also occur when you use the `erase_ship.yaml` configuration?

**Comment by YuyangXueEd** [comment]
Yes it still has the same problem when I tested with "erase_shop.yaml". 

Would you please help me to test it by cloning a clean repo? I did not change anything but get this error.

> I haven't encountered this error before. Does this error also occur when you use the `erase_ship.yaml` configuration?

**Comment by YuyangXueEd** [comment]
![image](https://github.com/user-attachments/assets/71015042-3798-47e3-9cb5-54a3e49a0bb3)
May I ask is this the correct path for generated image data and masks? If not, I may need to make some edit on the `data_preparation_transformers.py` as well.

**Comment by YuyangXueEd** [comment]
Hi,

I solved the issue by downgrade the package versions to:
```
pip install diffusers==0.22.0 transformers==4.38.1 huggingface_hub==0.25.2
```
It seems the diffusers library updated a lot of the attention process, removed the `scale` parameter.

I will closed the issue. Thanks.
